# Generated by Django 2.1.4 on 2019-01-25 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='height_mm',
            field=models.FloatField(default=0, verbose_name='Height (mm)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='length_mm',
            field=models.FloatField(default=0, verbose_name='Length (mm)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='width_mm',
            field=models.FloatField(default=0, verbose_name='Depth (mm)'),
        ),
        migrations.AlterField(
            model_name='historicalarticle',
            name='height_mm',
            field=models.FloatField(default=0, verbose_name='Height (mm)'),
        ),
        migrations.AlterField(
            model_name='historicalarticle',
            name='length_mm',
            field=models.FloatField(default=0, verbose_name='Length (mm)'),
        ),
        migrations.AlterField(
            model_name='historicalarticle',
            name='width_mm',
            field=models.FloatField(default=0, verbose_name='Depth (mm)'),
        ),
    ]
