# Generated by Django 2.1.1 on 2019-01-31 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20190125_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='vat',
            field=models.FloatField(default=0, verbose_name='VAT'),
        ),
        migrations.AlterField(
            model_name='historicalarticle',
            name='vat',
            field=models.FloatField(default=0, verbose_name='VAT'),
        ),
    ]
