# Generated by Django 2.1 on 2019-01-29 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20190125_0825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='descriptor_code',
        ),
        migrations.RemoveField(
            model_name='historicalarticle',
            name='descriptor_code',
        ),
        migrations.AddField(
            model_name='article',
            name='package_type',
            field=models.CharField(blank=True, max_length=128, verbose_name='Package Type'),
        ),
        migrations.AddField(
            model_name='historicalarticle',
            name='package_type',
            field=models.CharField(blank=True, max_length=128, verbose_name='Package Type'),
        ),
        migrations.AddField(
            model_name='historicalmerchantarticle',
            name='delisted',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='historicalmerchantarticle',
            name='last_order_date',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='historicalmerchantarticle',
            name='listed',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='merchantarticle',
            name='delisted',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='merchantarticle',
            name='last_order_date',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='merchantarticle',
            name='listed',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
