# Generated by Django 2.1 on 2019-01-29 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20190129_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='descriptor_code',
            field=models.CharField(blank=True, max_length=64, verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='historicalarticle',
            name='descriptor_code',
            field=models.CharField(blank=True, max_length=64, verbose_name='Type'),
        ),
    ]
