# Generated by Django 2.1 on 2019-01-29 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20190129_1514'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalmerchantarticle',
            old_name='last_order_date',
            new_name='last_date_to_order',
        ),
        migrations.RenameField(
            model_name='merchantarticle',
            old_name='last_order_date',
            new_name='last_date_to_order',
        ),
    ]
