# Generated by Django 2.1 on 2019-01-29 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20190129_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalmerchantarticle',
            name='delisted',
        ),
        migrations.RemoveField(
            model_name='merchantarticle',
            name='delisted',
        ),
    ]
