# Generated by Django 2.1 on 2019-01-04 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20190125_0825'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=128)),
                ('url', models.CharField(max_length=256)),
                ('is_public', models.BooleanField()),
                ('introduction', models.CharField(max_length=1024)),
                ('title', models.CharField(max_length=256)),
                ('metadescription', models.CharField(max_length=1024)),
                ('removed_date', models.DateTimeField()),
                ('parentcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='web.ProductCategory')),
            ],
        ),
        
    ]
