# Generated by Django 2.1 on 2019-01-04 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0032_auto_20190104_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='category_id',
        ),
    ]
