# Generated by Django 2.1.1 on 2019-02-04 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0034_auto_20190104_1400'),
        ('web', '0003_auto_20190131_0906'),
    ]

    operations = [
    ]
