# Generated by Django 2.1 on 2019-02-06 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0035_merge_20190204_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='introduction',
            field=models.CharField(max_length=1024, verbose_name='Intro'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='is_public',
            field=models.BooleanField(verbose_name='Is Public'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='metadescription',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Meta Description'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Category Name'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='parentcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='web.ProductCategory', verbose_name='Parent Category'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='removed_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Removed'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='title',
            field=models.CharField(max_length=256, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='url',
            field=models.CharField(max_length=256, verbose_name='Category URL'),
        ),
    ]
