# Generated by Django 2.1.1 on 2019-02-12 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20190129_1639'),
        ('web', '0036_auto_20190206_1339'),
    ]

    operations = [
    ]
