# Generated by Django 2.1.1 on 2019-02-14 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0037_merge_20190212_0830'),
        ('web', '0037_merge_20190207_1433'),
    ]

    operations = [
    ]
