# Generated by Django 2.1.1 on 2019-02-18 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0039_auto_20190214_1012'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='product_category',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='web.ProductCategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='web.ProductCategory'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='Category Name'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='url',
            field=models.CharField(max_length=256, unique=True, verbose_name='Category URL'),
        ),
    ]
