# Generated by Django 2.1.1 on 2019-02-19 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0040_auto_20190218_1237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tagtarget',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='parenttag',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='tagtype',
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='products', to='web.Tag'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='categories', to='web.Tag'),
        ),
        migrations.DeleteModel(
            name='TagTarget',
        ),
        migrations.DeleteModel(
            name='TagType',
        ),
    ]
