# Generated by Django 2.1.1 on 2019-02-21 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0042_auto_20190219_1159'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='valid_brand',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='valid_image',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='valid_merchantarticle',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='valid_price',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='valid_volume',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='valid_weight',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='valid_brand',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='valid_image',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='valid_merchantarticle',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='valid_price',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='valid_volume',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='valid_weight',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
