# Generated by Django 2.1.1 on 2019-03-05 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0045_auto_20190227_0934'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='article',
            name='web_article_categor_006394_idx',
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['category', 'name', 'gtin', 'source'], name='web_article_categor_5fa3c8_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['product_id', 'name', 'brand_name'], name='web_product_product_738929_idx'),
        ),
    ]
