# Generated by Django 2.1.7 on 2019-03-07 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0047_auto_20190306_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmerchantarticle',
            name='availability_status',
            field=models.CharField(default='', max_length=100, verbose_name='Availability status'),
        ),
        migrations.AlterField(
            model_name='historicalmerchantarticle',
            name='external_id',
            field=models.CharField(max_length=256, verbose_name='External ID'),
        ),
        migrations.AlterField(
            model_name='historicalmerchantarticle',
            name='last_date_to_order',
            field=models.CharField(blank=True, max_length=20, verbose_name='Last date to order'),
        ),
        migrations.AlterField(
            model_name='historicalmerchantarticle',
            name='listed',
            field=models.CharField(blank=True, max_length=20, verbose_name='Listed'),
        ),
        migrations.AlterField(
            model_name='historicalmerchantarticle',
            name='merchant_name',
            field=models.CharField(max_length=256, verbose_name='Merchant name'),
        ),
        migrations.AlterField(
            model_name='merchantarticle',
            name='availability_status',
            field=models.CharField(default='', max_length=100, verbose_name='Availability status'),
        ),
        migrations.AlterField(
            model_name='merchantarticle',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creation date'),
        ),
        migrations.AlterField(
            model_name='merchantarticle',
            name='external_id',
            field=models.CharField(max_length=256, verbose_name='External ID'),
        ),
        migrations.AlterField(
            model_name='merchantarticle',
            name='last_date_to_order',
            field=models.CharField(blank=True, max_length=20, verbose_name='Last date to order'),
        ),
        migrations.AlterField(
            model_name='merchantarticle',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Last modified'),
        ),
        migrations.AlterField(
            model_name='merchantarticle',
            name='listed',
            field=models.CharField(blank=True, max_length=20, verbose_name='Listed'),
        ),
        migrations.AlterField(
            model_name='merchantarticle',
            name='merchant_name',
            field=models.CharField(max_length=256, verbose_name='Merchant name'),
        ),
    ]
