# Generated by Django 2.1.7 on 2019-03-08 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0048_auto_20190307_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(help_text='Industri category (GS1)', max_length=100, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='article',
            name='child_gtin',
            field=models.CharField(blank=True, default='', help_text='If this is a package, what GTIN does the package contain?', max_length=14, verbose_name='Child GTIN'),
        ),
        migrations.AlterField(
            model_name='article',
            name='consumer_unit',
            field=models.BooleanField(default=False, help_text='Should this article be available to consumers?', verbose_name='Consumer unit'),
        ),
        migrations.AlterField(
            model_name='article',
            name='descriptor_code',
            field=models.CharField(choices=[('BASE_UNIT_OR_EACH', 'BASE_UNIT_OR_EACH'), ('CASE', 'CASE'), ('1/4', '1/4'), ('1/2', '1/2'), ('PALLET', 'PALLET')], help_text='What type of article is this?', max_length=64, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='article',
            name='quantity_of_lower_layer',
            field=models.IntegerField(blank=True, default=0, help_text='How many of that GTIN does it contain?', verbose_name='Quantity of Lower Layer'),
        ),
        migrations.AlterField(
            model_name='historicalarticle',
            name='category',
            field=models.CharField(help_text='Industri category (GS1)', max_length=100, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='historicalarticle',
            name='child_gtin',
            field=models.CharField(blank=True, default='', help_text='If this is a package, what GTIN does the package contain?', max_length=14, verbose_name='Child GTIN'),
        ),
        migrations.AlterField(
            model_name='historicalarticle',
            name='consumer_unit',
            field=models.BooleanField(default=False, help_text='Should this article be available to consumers?', verbose_name='Consumer unit'),
        ),
        migrations.AlterField(
            model_name='historicalarticle',
            name='descriptor_code',
            field=models.CharField(choices=[('BASE_UNIT_OR_EACH', 'BASE_UNIT_OR_EACH'), ('CASE', 'CASE'), ('1/4', '1/4'), ('1/2', '1/2'), ('PALLET', 'PALLET')], help_text='What type of article is this?', max_length=64, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='historicalarticle',
            name='quantity_of_lower_layer',
            field=models.IntegerField(blank=True, default=0, help_text='How many of that GTIN does it contain?', verbose_name='Quantity of Lower Layer'),
        ),
    ]
