# Generated by Django 2.1.7 on 2019-03-11 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0049_auto_20190308_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='whitelisted',
            field=models.BooleanField(default=False, verbose_name='Whitelisted'),
        ),
        migrations.AddField(
            model_name='historicalarticle',
            name='whitelisted',
            field=models.BooleanField(default=False, verbose_name='Whitelisted'),
        ),
    ]
