# Generated by Django 2.1 on 2019-03-13 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0051_auto_20190311_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmerchantarticle',
            name='number_of_consumerunits',
            field=models.IntegerField(blank=True, default=0, help_text='How many of that GTIN does it contain?', verbose_name='Number of consumer units'),
        ),
        migrations.AddField(
            model_name='historicalmerchantarticle',
            name='orderunit_gtin',
            field=models.CharField(max_length=14, null=True, verbose_name='Orderunit GTIN'),
        ),
        migrations.AddField(
            model_name='merchantarticle',
            name='number_of_consumerunits',
            field=models.IntegerField(blank=True, default=0, help_text='How many of that GTIN does it contain?', verbose_name='Number of consumer units'),
        ),
        migrations.AddField(
            model_name='merchantarticle',
            name='orderunit_gtin',
            field=models.CharField(max_length=14, null=True, verbose_name='Orderunit GTIN'),
        ),
        migrations.AlterField(
            model_name='historicalmerchantarticle',
            name='article_gtin',
            field=models.CharField(max_length=14, null=True, verbose_name='Consumer Article GTIN'),
        ),
        migrations.AlterField(
            model_name='merchantarticle',
            name='article_gtin',
            field=models.CharField(max_length=14, null=True, verbose_name='Consumer Article GTIN'),
        ),
    ]
