# Generated by Django 2.1.7 on 2019-03-12 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0051_auto_20190311_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='introduction',
            field=models.TextField(verbose_name='Intro'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='url',
            field=models.CharField(max_length=256, verbose_name='Category URL'),
        ),
    ]
