# Generated by Django 2.1.7 on 2019-03-15 09:03

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0052_auto_20190312_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='allergen_statement',
            field=models.TextField(blank=True, default='', verbose_name='Allergen Statement'),
        ),
        migrations.AddField(
            model_name='article',
            name='allergens',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, verbose_name='Allergens'),
        ),
        migrations.AddField(
            model_name='historicalarticle',
            name='allergen_statement',
            field=models.TextField(blank=True, default='', verbose_name='Allergen Statement'),
        ),
        migrations.AddField(
            model_name='historicalarticle',
            name='allergens',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, verbose_name='Allergens'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='allergen_statement',
            field=models.TextField(blank=True, default='', verbose_name='Allergen Statement'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='allergens',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, verbose_name='Allergens'),
        ),
        migrations.AddField(
            model_name='product',
            name='allergen_statement',
            field=models.TextField(blank=True, default='', verbose_name='Allergen Statement'),
        ),
        migrations.AddField(
            model_name='product',
            name='allergens',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, verbose_name='Allergens'),
        ),
    ]
