# Generated by Django 2.1.7 on 2019-03-20 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0053_auto_20190315_0903'),
        ('web', '0052_auto_20190313_1743'),
    ]

    operations = [
    ]
