# Generated by Django 2.1.7 on 2019-03-20 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0054_merge_20190320_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='height_mm',
            field=models.FloatField(blank=True, null=True, verbose_name='Height (mm)'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='length_mm',
            field=models.FloatField(blank=True, null=True, verbose_name='Length (mm)'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='volume_dm3',
            field=models.FloatField(blank=True, max_length=10, null=True, verbose_name='Volume (dm³)'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='weight_g',
            field=models.FloatField(blank=True, null=True, verbose_name='Weight (g)'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='width_mm',
            field=models.FloatField(blank=True, null=True, verbose_name='Depth (mm)'),
        ),
        migrations.AddField(
            model_name='product',
            name='height_mm',
            field=models.FloatField(blank=True, null=True, verbose_name='Height (mm)'),
        ),
        migrations.AddField(
            model_name='product',
            name='length_mm',
            field=models.FloatField(blank=True, null=True, verbose_name='Length (mm)'),
        ),
        migrations.AddField(
            model_name='product',
            name='volume_dm3',
            field=models.FloatField(blank=True, max_length=10, null=True, verbose_name='Volume (dm³)'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight_g',
            field=models.FloatField(blank=True, null=True, verbose_name='Weight (g)'),
        ),
        migrations.AddField(
            model_name='product',
            name='width_mm',
            field=models.FloatField(blank=True, null=True, verbose_name='Depth (mm)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='vat',
            field=models.FloatField(choices=[(0.0, 0.0), (6.0, 6.0), (12.0, 12.0), (25.0, 25.0)], default=0, verbose_name='VAT'),
        ),
        migrations.AlterField(
            model_name='historicalarticle',
            name='vat',
            field=models.FloatField(choices=[(0.0, 0.0), (6.0, 6.0), (12.0, 12.0), (25.0, 25.0)], default=0, verbose_name='VAT'),
        ),
    ]
