# Generated by Django 2.1 on 2019-04-18 12:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0055_auto_20190320_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleimage',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Modified'),
        ),
        migrations.AddField(
            model_name='historicalarticleimage',
            name='last_modified',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, verbose_name='Last Modified'),
            preserve_default=False,
        ),
    ]
