# Generated by Django 2.1 on 2019-05-02 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0056_auto_20190418_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='recycle_fee',
            field=models.FloatField(default=0.0, verbose_name='Recycle Fee'),
        ),
        migrations.AddField(
            model_name='historicalarticle',
            name='recycle_fee',
            field=models.FloatField(default=0.0, verbose_name='Recycle Fee'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='recycle_fee',
            field=models.FloatField(default=0.0, verbose_name='Recycle Fee'),
        ),
        migrations.AddField(
            model_name='product',
            name='recycle_fee',
            field=models.FloatField(default=0.0, verbose_name='Recycle Fee'),
        ),
    ]
