# Generated by Django 2.1 on 2019-05-03 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0058_auto_20190430_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='adultProduct',
            field=models.BooleanField(default=False, verbose_name='Adult Product'),
        ),
        migrations.AddField(
            model_name='historicalarticle',
            name='adultProduct',
            field=models.BooleanField(default=False, verbose_name='Adult Product'),
        ),
    ]
