# Generated by Django 2.1 on 2019-05-06 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0059_auto_20190503_1359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='adultProduct',
            new_name='adult_product',
        ),
        migrations.RenameField(
            model_name='historicalarticle',
            old_name='adultProduct',
            new_name='adult_product',
        ),
        migrations.RenameField(
            model_name='historicalproduct',
            old_name='adultProduct',
            new_name='adult_product',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='adultProduct',
            new_name='adult_product',
        ),
    ]
