# Generated by Django 2.2 on 2019-05-06 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0060_auto_20190506_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproductdetail',
            name='first_enabled',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productdetail',
            name='first_enabled',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
