# Generated by Django 2.1 on 2019-05-07 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0057_auto_20190502_0858'),
        ('web', '0060_auto_20190506_1329'),
    ]

    operations = [
    ]
