# Generated by Django 2.1 on 2019-05-07 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0061_merge_20190507_1456'),
        ('web', '0058_auto_20190503_1114'),
    ]

    operations = [
    ]
