# Generated by Django 2.2 on 2019-05-21 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0063_auto_20190520_0733'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproductdetail',
            name='orderfactor',
            field=models.BooleanField(default=False, verbose_name='Orderfactor'),
        ),
        migrations.AddField(
            model_name='productdetail',
            name='orderfactor',
            field=models.BooleanField(default=False, verbose_name='Orderfactor'),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='product_type',
            field=models.CharField(blank=True, choices=[('Normal', 'Normal'), ('Crossdocking', 'Crossdocking'), ('Nightorder', 'Nightorder')], default='Normal', max_length=128, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(blank=True, choices=[('Normal', 'Normal'), ('Crossdocking', 'Crossdocking'), ('Nightorder', 'Nightorder')], default='Normal', max_length=128, verbose_name='Type'),
        ),
    ]
