# Generated by Django 2.2 on 2019-05-21 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0064_auto_20190521_0703'),
        ('web', '0061_auto_20190506_1424'),
    ]

    operations = [
    ]
