# Generated by Django 2.2 on 2019-06-11 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0065_merge_20190521_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalmerchantarticle',
            name='number_of_consumerunits',
        ),
        migrations.RemoveField(
            model_name='historicalmerchantarticle',
            name='orderunit_gtin',
        ),
        migrations.RemoveField(
            model_name='merchantarticle',
            name='number_of_consumerunits',
        ),
        migrations.RemoveField(
            model_name='merchantarticle',
            name='orderunit_gtin',
        ),
        migrations.AlterField(
            model_name='historicalmerchantarticle',
            name='article_gtin',
            field=models.CharField(max_length=14, null=True, verbose_name='Article GTIN'),
        ),
        migrations.AlterField(
            model_name='merchantarticle',
            name='article_gtin',
            field=models.CharField(max_length=14, null=True, verbose_name='Article GTIN'),
        ),
    ]
