# Generated by Django 2.2 on 2019-06-11 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0066_auto_20190611_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchantarticle',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='merchant_articles', to='web.Article'),
        ),
    ]
