# Generated by Django 2.2 on 2019-06-25 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0068_auto_20190612_0854'),
        ('web', '0067_auto_20190619_0907'),
    ]

    operations = [
    ]
