# Generated by Django 2.2 on 2019-07-29 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0069_merge_20190625_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmerchantarticle',
            name='prefered',
            field=models.BooleanField(default=False, verbose_name='Preferred merchant'),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='net_content',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Net Content'),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='net_content_unit_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Net Content Unit Code'),
        ),
        migrations.AlterField(
            model_name='merchantarticle',
            name='prefered',
            field=models.BooleanField(default=False, verbose_name='Preferred merchant'),
        ),
        migrations.AlterField(
            model_name='product',
            name='net_content',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Net Content'),
        ),
        migrations.AlterField(
            model_name='product',
            name='net_content_unit_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Net Content Unit Code'),
        ),
    ]
