# Generated by Django 2.2 on 2019-08-15 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0070_auto_20190729_0753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalmerchantarticle',
            name='prefered',
        ),
        migrations.RemoveField(
            model_name='merchantarticle',
            name='prefered',
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='prefered_merchantarticle',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='web.MerchantArticle'),
        ),
        migrations.AddField(
            model_name='historicalproductdetail',
            name='prefered_merchantarticle',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='web.MerchantArticle'),
        ),
        migrations.AddField(
            model_name='product',
            name='prefered_merchantarticle',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='web.MerchantArticle'),
        ),
        migrations.AddField(
            model_name='productdetail',
            name='prefered_merchantarticle',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='web.MerchantArticle'),
        ),
    ]
