# Generated by Django 2.2.1 on 2019-08-07 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0070_auto_20190729_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='net_content',
            field=models.FloatField(null=True, verbose_name='Net Content'),
        ),
        migrations.AlterField(
            model_name='historicalarticle',
            name='net_content',
            field=models.FloatField(null=True, verbose_name='Net Content'),
        ),
    ]
