# Generated by Django 2.2.1 on 2019-08-07 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0071_auto_20190807_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproduct',
            name='net_content',
            field=models.FloatField(blank=True, null=True, verbose_name='Net Content'),
        ),
        migrations.AlterField(
            model_name='product',
            name='net_content',
            field=models.FloatField(blank=True, null=True, verbose_name='Net Content'),
        ),
    ]
