# Generated by Django 2.2.1 on 2019-08-15 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0071_auto_20190815_0813'),
        ('web', '0072_auto_20190807_0957'),
    ]

    operations = [
    ]
