# Generated by Django 2.2.4 on 2019-09-22 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0075_auto_20190922_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='currency',
            field=models.CharField(default='SEK', max_length=5),
        ),
        migrations.AddField(
            model_name='historicalarticle',
            name='currency',
            field=models.CharField(default='SEK', max_length=5),
        ),
    ]
